{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.hexay",
    "module": "ktrs-gradle-plugin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.3.0.jar",
          "url": "ktrs-gradle-plugin-0.3.0.jar",
          "size": 66865,
          "sha512": "10cf8258de7b3f0336b53328c4a03605ee575cb86cb05a875d909c103b7d792e28a29c7d60d053c6d12088ffea06c02c1135879f12f530d36775cead2aa27727",
          "sha256": "8c1f553558265970b415dc85286d94b55929aa18375e7a52120789800c14b4df",
          "sha1": "612faf92fd1d4295e6cfca18f2abfb0f164137be",
          "md5": "bbc9a540c2a275f6136adc9fc038fbcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.hexay",
          "module": "ktrs",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.3.0.jar",
          "url": "ktrs-gradle-plugin-0.3.0.jar",
          "size": 66865,
          "sha512": "10cf8258de7b3f0336b53328c4a03605ee575cb86cb05a875d909c103b7d792e28a29c7d60d053c6d12088ffea06c02c1135879f12f530d36775cead2aa27727",
          "sha256": "8c1f553558265970b415dc85286d94b55929aa18375e7a52120789800c14b4df",
          "sha1": "612faf92fd1d4295e6cfca18f2abfb0f164137be",
          "md5": "bbc9a540c2a275f6136adc9fc038fbcd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.3.0-javadoc.jar",
          "url": "ktrs-gradle-plugin-0.3.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.3.0-sources.jar",
          "url": "ktrs-gradle-plugin-0.3.0-sources.jar",
          "size": 17438,
          "sha512": "e29c3f98245e9a8096193b4d91183a4ee94c56c95e6c79e737a46f11c78391dff6fdd873d447af7c902e93cee79f5c8266befc22b9ff6d160782f3eaf2968d52",
          "sha256": "defd07528728faf30b86334a44d8ab9c957a1a1ecd72c5eefe97987a0a95fcf7",
          "sha1": "0028b1491e33255cdbe7bfb54407f8357930d76d",
          "md5": "c6fcff317a7d64b4c89b0d4e4f9035c1"
        }
      ]
    }
  ]
}
