report.ktlint.name=Ktlint
report.ktlint.description=Report on coding style conventions.
report.ktlint.title=Ktlint Results
report.ktlint.ktlintlink=The following document contains the results of
report.ktlint.summary=Summary
report.ktlint.files=Files
report.ktlint.errors=Errors
report.ktlint.file=File
report.ktlint.details=Details
report.ktlint.detail=Detail
report.ktlint.ruleId=Rule ID
report.ktlint.line=Line
