<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>parent</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <modules>
    <module>module</module>
  </modules>
  <properties>
    <compose.rules.version>0.4.22</compose.rules.version>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.github.gantsign.maven</groupId>
          <artifactId>ktlint-maven-plugin</artifactId>
          <version>3.7.1</version>
          <configuration>
            <android>false</android>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>io.nlopez.compose.rules</groupId>
              <artifactId>ktlint</artifactId>
              <version>${compose.rules.version}</version>
            </dependency>
            <dependency>
              <groupId>com.pinterest.ktlint</groupId>
              <artifactId>ktlint-cli-reporter-html</artifactId>
              <version>1.8.0</version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
