#!/usr/bin/env bash
# Prints Formula/ktrs.rb for a release, from its SHA256SUMS (the tap is this repo:
# `brew tap hexay/ktrs https://github.com/Hexay/ktrs`). Run by the release workflow:
#   tools/release/homebrew-formula.sh v0.2.0 SHA256SUMS > Formula/ktrs.rb
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
tag=$1 sums=$2
# shellcheck source=release-assets.sh
source "$here/release-assets.sh"

target() {
  echo "      url \"$(asset_url "$1")\""
  echo "      sha256 \"$(asset_sha "$1")\""
}

cat <<EOF
# Generated by tools/release/homebrew-formula.sh for $tag; do not edit.
class Ktrs < Formula
  desc "Fast Kotlin formatter and linter, with drop-in ktfmt and ktlint executables"
  homepage "https://github.com/Hexay/ktrs"
  version "${tag#v}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
$(target aarch64-apple-darwin)
    end
    on_intel do
$(target x86_64-apple-darwin)
    end
  end

  on_linux do
    on_arm do
$(target aarch64-unknown-linux-musl)
    end
    on_intel do
$(target x86_64-unknown-linux-musl)
    end
  end

  conflicts_with "ktfmt", because: "both install a \`ktfmt\` executable"
  conflicts_with "ktlint", because: "both install a \`ktlint\` executable"

  def install
    bin.install "ktrs", "ktfmt", "ktlint"
  end

  test do
    assert_equal "fun f() = 1\n", pipe_output("#{bin}/ktfmt -", "fun  f( ) = 1\n")
    assert_equal "", pipe_output("#{bin}/ktlint --stdin --log-level=none", "fun f() = 1\n")
  end
end
EOF
