#!/usr/bin/env bash
# Prints Formula/ktrs.rb for a release, from its SHA256SUMS (the tap is this repo:
# `brew tap hexay/ktrs https://github.com/Hexay/ktrs`). Run by the release workflow:
#   tools/release/homebrew-formula.sh v0.2.0 SHA256SUMS > Formula/ktrs.rb
set -euo pipefail
tag=$1 sums=$2
base="https://github.com/Hexay/ktrs/releases/download/$tag"

sha() {
  local name="ktrs-$tag-$1.tar.gz" sum
  sum=$(awk -v n="$name" '$2 == n { print $1 }' "$sums")
  [[ -n $sum ]] || { echo "no checksum for $name in $sums" >&2; exit 1; }
  echo "$sum"
}

cat <<EOF
# Generated by tools/release/homebrew-formula.sh for $tag; do not edit.
class Ktrs < Formula
  desc "Fast Kotlin formatter, byte-identical to ktfmt 0.64 (ktrs, plus a drop-in ktfmt)"
  homepage "https://github.com/Hexay/ktrs"
  version "${tag#v}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "$base/ktrs-$tag-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$base/ktrs-$tag-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$base/ktrs-$tag-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "$base/ktrs-$tag-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  conflicts_with "ktfmt", because: "both install a \`ktfmt\` executable"

  def install
    bin.install "ktrs", "ktfmt"
  end

  test do
    assert_equal "fun f() = 1\n", pipe_output("#{bin}/ktfmt -", "fun  f( ) = 1\n")
  end
end
EOF
