{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.hexay",
    "module": "ktrs-gradle-plugin",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.5.0.jar",
          "url": "ktrs-gradle-plugin-0.5.0.jar",
          "size": 195321,
          "sha512": "c4c391c1d5edc9b4261069eeb852fd0b64bc799e733bbca02e5a34ba0a8dcf28e82f48065686ecb755057d8b39dd274c7b88d22a1be315b86b1a4624c6a34340",
          "sha256": "ef059abcec0418dd50008a90ce2d4b07770ef11cd433b7a62750674bca47a881",
          "sha1": "4a4125a06374c0f89eaf6724cabcfef57d48e1d4",
          "md5": "7e1e4980f57a049c33c0bdb742db9836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.hexay",
          "module": "ktrs",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.5.0.jar",
          "url": "ktrs-gradle-plugin-0.5.0.jar",
          "size": 195321,
          "sha512": "c4c391c1d5edc9b4261069eeb852fd0b64bc799e733bbca02e5a34ba0a8dcf28e82f48065686ecb755057d8b39dd274c7b88d22a1be315b86b1a4624c6a34340",
          "sha256": "ef059abcec0418dd50008a90ce2d4b07770ef11cd433b7a62750674bca47a881",
          "sha1": "4a4125a06374c0f89eaf6724cabcfef57d48e1d4",
          "md5": "7e1e4980f57a049c33c0bdb742db9836"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.5.0-javadoc.jar",
          "url": "ktrs-gradle-plugin-0.5.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktrs-gradle-plugin-0.5.0-sources.jar",
          "url": "ktrs-gradle-plugin-0.5.0-sources.jar",
          "size": 50255,
          "sha512": "aa71d295933f1c4b3044a94cb58995ed14e5ff823e95053fee83ded2f27745e9e17fdcdd77176d8010c0e25904110bca08f281a69d56c8318b45c245f16e656b",
          "sha256": "ee8b8a1a28addc3ff39c4056f56e08ca67c7aa1a8b38fb436d6db938d41c58ab",
          "sha1": "05f320bcbc93d74c921abdd40645ae49d2ef8746",
          "md5": "2a9b6957e23b85b62fb7b125006fd4f8"
        }
      ]
    }
  ]
}
