# Generated by tools/release/homebrew-formula.sh for v0.2.0; do not edit.
class Ktrs < Formula
  desc "Fast Kotlin formatter, byte-identical to ktfmt 0.64 (ktrs, plus a drop-in ktfmt)"
  homepage "https://github.com/Hexay/ktrs"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.2.0/ktrs-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "21751229219f4520ee93d3a38bde20eabd96f91f433b8e0589159b8773ba08aa"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.2.0/ktrs-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "26eed4c23290becab315572c208f83b1925a2946646779c4d2111cf376482f44"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.2.0/ktrs-v0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a90e34b3be59e39015ae2144222747992ea8d1ab8720fd8e2ee597bfc55b6548"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.2.0/ktrs-v0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b28c09ebb80c37ac8038dd3d238faa1e007188eeb0141ad106fb644df37a16a3"
    end
  end

  conflicts_with "ktfmt", because: "both install a `ktfmt` executable"

  def install
    bin.install "ktrs", "ktfmt"
  end

  test do
    assert_equal "fun f() = 1\n", pipe_output("#{bin}/ktfmt -", "fun  f( ) = 1\n")
  end
end
