# Generated by tools/release/homebrew-formula.sh for v0.5.0; do not edit.
class Ktrs < Formula
  desc "Fast Kotlin formatter and linter, with drop-in ktfmt and ktlint executables"
  homepage "https://github.com/Hexay/ktrs"
  version "0.5.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.0/ktrs-v0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "29f5191fd3c54aef423c64fad1197138b2c14d38762afe6d66b3e3288645d791"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.0/ktrs-v0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "cbbd3bc60b73945c2592ec71a2c47c8eacbc79cb2746ace7b82ba62b00524d05"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.0/ktrs-v0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4ca67a98fd404869fea0509db26cb868687a626f791adcf4b3fbe49b896b1c6b"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.0/ktrs-v0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "321dbd76fc381a2755f67d1d4f50b1aced075fe82c0050c749accfaf7d764660"
    end
  end

  conflicts_with "ktfmt", because: "both install a `ktfmt` executable"
  conflicts_with "ktlint", because: "both install a `ktlint` executable"

  def install
    bin.install "ktrs", "ktfmt", "ktlint"
  end

  test do
    assert_equal "fun f() = 1\n", pipe_output("#{bin}/ktfmt -", "fun  f( ) = 1\n")
    assert_equal "", pipe_output("#{bin}/ktlint --stdin --log-level=none", "fun f() = 1\n")
  end
end
