# Generated by tools/release/homebrew-formula.sh for v0.5.1; do not edit.
class Ktrs < Formula
  desc "Fast Kotlin formatter and linter, with drop-in ktfmt and ktlint executables"
  homepage "https://github.com/Hexay/ktrs"
  version "0.5.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.1/ktrs-v0.5.1-aarch64-apple-darwin.tar.gz"
      sha256 "b564b2e1a95854359112a487e3c72bb8667cd476fee25fa5335388961c7d0a87"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.1/ktrs-v0.5.1-x86_64-apple-darwin.tar.gz"
      sha256 "24955b409b5af7a5dad3ef634591b678a2c1ca34aef2dfe0ff6b3a4b92f33a33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.1/ktrs-v0.5.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5621f90970a75d98db0dc2420a2cf20377bd4462ce98d6fcddcb617c3dccb682"
    end
    on_intel do
      url "https://github.com/Hexay/ktrs/releases/download/v0.5.1/ktrs-v0.5.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "753685e3e83be8c3a71569ca0a01109eed2cf9cd68f2e4c60a7de65d38ff5538"
    end
  end

  conflicts_with "ktfmt", because: "both install a `ktfmt` executable"
  conflicts_with "ktlint", because: "both install a `ktlint` executable"

  def install
    bin.install "ktrs", "ktfmt", "ktlint"
  end

  test do
    assert_equal "fun f() = 1\n", pipe_output("#{bin}/ktfmt -", "fun  f( ) = 1\n")
    assert_equal "", pipe_output("#{bin}/ktlint --stdin --log-level=none", "fun f() = 1\n")
  end
end
