"""Regenerates src/unicode_tables.rs from the JFlex char maps of the pinned generated lexers.

Usage: py -3 crates/ktrs-lexer/tools/gen_unicode_tables.py
Only non-ASCII code points are tabulated; ASCII is handled inline by the lexers.
"""
import os
import re

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
SRC = os.path.join(ROOT, 'third_party', 'kotlin', 'compiler', 'psi', 'parser', 'src', 'org', 'jetbrains', 'kotlin')
OUT = os.path.join(ROOT, 'crates', 'ktrs_lexer', 'src', 'unicode_tables.rs')


def java_str(s):
    out, i = [], 0
    while i < len(s):
        if s[i] != '\\':
            out.append(s[i]); i += 1
        elif s[i + 1] == 'u':
            out.append(chr(int(s[i + 2:i + 6], 16))); i += 6
        elif s[i + 1] in '01234567':
            t = re.match(r'[0-7]{1,3}', s[i + 1:]).group(0)
            if len(t) == 3 and t[0] > '3':
                t = t[:2]
            out.append(chr(int(t, 8))); i += 1 + len(t)
        else:
            out.append({'n': '\n', 't': '\t', 'r': '\r', 'f': '\f', 'b': '\b'}.get(s[i + 1], s[i + 1])); i += 2
    return ''.join(out)


def unpack(src, name):
    res = []
    for p in re.findall(r'%s_PACKED_\d+ =\s*((?:"(?:[^"\\]|\\.)*"\s*\+?\s*)+);' % name, src):
        s = ''.join(java_str(x) for x in re.findall(r'"((?:[^"\\]|\\.)*)"', p))
        for i in range(0, len(s), 2):
            res += [ord(s[i + 1])] * ord(s[i])
    return res


def class_ranges(path, sample):
    """Non-ASCII ranges whose JFlex char class equals the class of `sample`."""
    src = open(path, encoding='utf-8').read()
    top, blocks = unpack(src, 'ZZ_CMAP_TOP'), unpack(src, 'ZZ_CMAP_BLOCKS')

    def cls(cp):
        return blocks[cp] if cp < 256 else blocks[top[cp >> 8] | (cp & 255)]

    want, ranges = cls(sample), []
    for cp in range(0x80, 0x110000):
        if 0xD800 <= cp <= 0xDFFF or cls(cp) != want:
            continue
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def table(name, doc, ranges):
    lines = ['/// %s' % doc, '#[rustfmt::skip]', 'pub(crate) static %s: &[(u32, u32)] = &[' % name]
    for i in range(0, len(ranges), 5):
        lines.append('    ' + ' '.join('(0x%x, 0x%x),' % (a, b) for a, b in ranges[i:i + 5]))
    lines.append('];')
    return '\n'.join(lines)


def main():
    kotlin = os.path.join(SRC, 'lexer', '_JetLexer.java')
    kdoc = os.path.join(SRC, 'kdoc', 'lexer', '_KDocLexer.java')
    parts = [
        '//! @generated by `crates/ktrs-lexer/tools/gen_unicode_tables.py` from the JFlex char maps. Do not edit.',
        table('KOTLIN_LETTER', 'Non-ASCII `[:letter:]` of `Kotlin.flex`.', class_ranges(kotlin, 0xC0)),
        table('KOTLIN_DIGIT', 'Non-ASCII `[:digit:]` of `Kotlin.flex`.', class_ranges(kotlin, 0x660)),
        table('KDOC_JLETTER', 'Non-ASCII `[:jletter:]` of `KDoc.flex`.', class_ranges(kdoc, 0xC0)),
    ]
    with open(OUT, 'w', newline='\n') as f:
        f.write('\n\n'.join(parts) + '\n')


main()
