[package]
name = "ktrs_fmt"
description = "Kotlin formatter producing byte-identical output to ktfmt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ktrs_syntax.workspace = true
ktrs_lexer.workspace = true
ktrs_parser.workspace = true
ktrs_psi.workspace = true

[dev-dependencies]
expect-test.workspace = true
mimalloc.workspace = true
