//! Generates `kt-syntax/src/generated/kinds.rs`: the facade's kinds as associated constants of its opaque
//! `SyntaxKind`, and the tables behind `name`/`from_name` (research/36, "Stability policy").

use std::fmt::Write;

use crate::codegen::Kind;

pub(crate) fn render(kinds: &[Kind]) -> String {
    let mut s = String::new();
    s.push_str("//! @generated by `cargo xtask codegen` from `ktrs-syntax/kinds.tsv`. Do not edit.\n\n");
    s.push_str("use ktrs_syntax::SyntaxKind as Raw;\n\nuse crate::SyntaxKind;\n\n");
    s.push_str("impl SyntaxKind {\n");
    for k in kinds {
        let what = if k.is_token { "token" } else { "node" };
        writeln!(s, "    /// The `{}` {what}.", k.name).unwrap();
        writeln!(s, "    pub const {0}: SyntaxKind = SyntaxKind(Raw::{0});", k.name).unwrap();
    }
    s.push_str("}\n\n");

    s.push_str("/// Kind names, indexed by the internal kind's discriminant.\n");
    writeln!(s, "pub(crate) const NAMES: [&str; {}] = [", kinds.len()).unwrap();
    for k in kinds {
        writeln!(s, "    {:?},", k.name).unwrap();
    }
    s.push_str("];\n\n");

    let mut sorted: Vec<&str> = kinds.iter().map(|k| k.name.as_str()).collect();
    sorted.sort_unstable();
    s.push_str("/// Every kind, sorted by name.\n");
    writeln!(s, "pub(crate) const BY_NAME: [(&str, SyntaxKind); {}] = [", kinds.len()).unwrap();
    for name in sorted {
        writeln!(s, "    ({name:?}, SyntaxKind::{name}),").unwrap();
    }
    s.push_str("];\n");
    s
}
