//! Generates `ktrs-syntax/src/generated/kinds.rs` from `ktrs-syntax/kinds.tsv`,
//! which `tools/psi-dump/psi-dump.sh kinds` extracts from the pinned Kotlin compiler.

use std::{collections::HashSet, fmt::Write, fs, path::Path};

pub(crate) struct Kind {
    pub(crate) name: String,
    debug_name: String,
    pub(crate) is_token: bool,
    keyword: Option<(String, bool)>,
}

pub(crate) fn run(root: &Path) -> Result<(), String> {
    let crate_dir = root.join("crates/ktrs-syntax");
    let tsv = fs::read_to_string(crate_dir.join("kinds.tsv")).map_err(|e| format!("kinds.tsv: {e}"))?;
    let kinds = parse_tsv(&tsv)?;
    let out = render(&kinds);
    crate::write_if_changed(&crate_dir.join("src/generated/kinds.rs"), &out)?;
    crate::write_if_changed(&root.join("crates/kt-syntax/src/generated/kinds.rs"), &crate::codegen_facade::render(&kinds))
}

fn parse_tsv(tsv: &str) -> Result<Vec<Kind>, String> {
    let mut kinds = Vec::new();
    let mut names = HashSet::new();
    for (i, line) in tsv.lines().enumerate().skip(1) {
        let cols: Vec<&str> = line.split('\t').collect();
        let [owner, field, debug_name, _class, shape, keyword, soft] = cols[..] else {
            return Err(format!("kinds.tsv:{}: expected 7 columns", i + 1));
        };
        let name = match owner {
            "KDocTokens" if !field.starts_with("KDOC_") => format!("KDOC_{field}"),
            _ => field.to_string(),
        };
        if !names.insert(name.clone()) {
            return Err(format!("kinds.tsv:{}: duplicate kind {name}", i + 1));
        }
        kinds.push(Kind {
            name,
            debug_name: debug_name.replace("\\n", "\n").replace("\\t", "\t").replace("\\\\", "\\"),
            is_token: shape == "token",
            keyword: (!keyword.is_empty()).then(|| (keyword.to_string(), soft == "true")),
        });
    }
    Ok(kinds)
}

fn render(kinds: &[Kind]) -> String {
    let mut s = String::new();
    s.push_str("//! @generated by `cargo xtask codegen` from `kinds.tsv`. Do not edit.\n\n");
    s.push_str("#[allow(non_camel_case_types, clippy::upper_case_acronyms)]\n");
    s.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n#[repr(u16)]\n");
    s.push_str("pub enum SyntaxKind {\n");
    for k in kinds {
        writeln!(s, "    {},", k.name).unwrap();
    }
    s.push_str("}\n\n");
    s.push_str("use SyntaxKind::*;\n\n");
    writeln!(s, "pub(crate) const ALL: [SyntaxKind; {}] = [", kinds.len()).unwrap();
    for k in kinds {
        writeln!(s, "    {},", k.name).unwrap();
    }
    s.push_str("];\n\nimpl SyntaxKind {\n");

    s.push_str("    /// Name the compiler's `IElementType.toString()` returns; used verbatim in PSI dumps.\n");
    s.push_str("    pub const fn debug_name(self) -> &'static str {\n        match self {\n");
    for k in kinds {
        writeln!(s, "            {} => {:?},", k.name, k.debug_name).unwrap();
    }
    s.push_str("        }\n    }\n\n");

    s.push_str("    pub const fn is_token(self) -> bool {\n        matches!(\n            self,\n");
    let tokens: Vec<&str> = kinds.iter().filter(|k| k.is_token).map(|k| k.name.as_str()).collect();
    writeln!(s, "            {}", tokens.join("\n                | ")).unwrap();
    s.push_str("        )\n    }\n\n");

    for (fn_name, soft, doc) in [
        ("hard_keyword", false, "Reserved keyword the lexer emits for `text`."),
        ("soft_keyword", true, "Soft or modifier keyword for `text`; lexed as IDENTIFIER, remapped by the parser."),
    ] {
        writeln!(s, "    /// {doc}").unwrap();
        writeln!(s, "    pub fn {fn_name}(text: &str) -> Option<SyntaxKind> {{").unwrap();
        // Byte-slice patterns compile to a length/byte decision tree; `&str` arms are compared one by one.
        s.push_str("        Some(match text.as_bytes() {\n");
        for k in kinds.iter().filter(|k| matches!(&k.keyword, Some((_, is_soft)) if *is_soft == soft)) {
            let (text, _) = k.keyword.as_ref().unwrap();
            let bytes: Vec<String> = text.bytes().map(|b| format!("{:?}", b as char).replacen('\'', "b'", 1)).collect();
            writeln!(s, "            [{}] => {}, // {text}", bytes.join(", "), k.name).unwrap();
        }
        s.push_str("            _ => return None,\n        })\n    }\n\n");
    }

    s.push_str("    pub fn keyword_text(self) -> Option<&'static str> {\n        Some(match self {\n");
    for k in kinds {
        if let Some((text, _)) = &k.keyword {
            writeln!(s, "            {} => {text:?},", k.name).unwrap();
        }
    }
    s.push_str("            _ => return None,\n        })\n    }\n}\n");
    s
}
