//! Port of `FormattingOptions.kt` (whole file), without its private `experimentalEngine` (not ported).

use std::fmt;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FormattingOptions {
    /// ktfmt breaks lines longer than maxWidth.
    pub max_width: i32,
    /// The size of the indent used when a new block is opened, in spaces.
    pub block_indent: i32,
    /// The size of the indent used when a line is broken because it's too long, in spaces.
    pub continuation_indent: i32,
    pub trailing_comma_management_strategy: TrailingCommaManagementStrategy,
    /// Whether ktfmt should remove imports that are not used.
    pub remove_unused_imports: bool,
    /// Whether to preserve user-authored line breaks inside lambda bodies.
    pub preserve_lambda_breaks: bool,
    /// Print the Ops generated by KotlinInputAstVisitor.
    pub debugging_print_ops_after_formatting: bool,
}

impl FormattingOptions {
    pub const DEFAULT_MAX_WIDTH: i32 = 100;
    pub const DEFAULT_BLOCK_INDENT: i32 = 2;
    pub const DEFAULT_CONTINUATION_INDENT: i32 = 4;

    /// The primary constructor with its Kotlin defaults.
    pub const fn new(block_indent: i32, continuation_indent: i32) -> FormattingOptions {
        FormattingOptions {
            max_width: Self::DEFAULT_MAX_WIDTH,
            block_indent,
            continuation_indent,
            trailing_comma_management_strategy: TrailingCommaManagementStrategy::Complete,
            remove_unused_imports: true,
            preserve_lambda_breaks: true,
            debugging_print_ops_after_formatting: false,
        }
    }

    /// Deprecated `(maxWidth, blockIndent, continuationIndent, manageTrailingCommas, ...)` constructor.
    pub fn with_manage_trailing_commas(
        max_width: i32,
        block_indent: i32,
        continuation_indent: i32,
        manage_trailing_commas: bool,
        remove_unused_imports: bool,
        debugging_print_ops_after_formatting: bool,
    ) -> FormattingOptions {
        FormattingOptions {
            max_width,
            block_indent,
            continuation_indent,
            trailing_comma_management_strategy: if manage_trailing_commas {
                TrailingCommaManagementStrategy::Complete
            } else {
                TrailingCommaManagementStrategy::None
            },
            remove_unused_imports,
            // Pinned to false to preserve the behavior callers of this deprecated constructor had.
            preserve_lambda_breaks: false,
            debugging_print_ops_after_formatting,
        }
    }

    /// Deprecated `(maxWidth, blockIndent, continuationIndent, trailingCommaManagementStrategy, ...)` constructor.
    pub fn with_strategy(
        max_width: i32,
        block_indent: i32,
        continuation_indent: i32,
        trailing_comma_management_strategy: TrailingCommaManagementStrategy,
        remove_unused_imports: bool,
        debugging_print_ops_after_formatting: bool,
    ) -> FormattingOptions {
        FormattingOptions {
            max_width,
            block_indent,
            continuation_indent,
            trailing_comma_management_strategy,
            remove_unused_imports,
            preserve_lambda_breaks: false,
            debugging_print_ops_after_formatting,
        }
    }

    pub fn manage_trailing_commas(&self) -> bool {
        self.trailing_comma_management_strategy != TrailingCommaManagementStrategy::None
    }

    pub fn to_builder(&self) -> Builder {
        Builder::new()
            .max_width(self.max_width)
            .block_indent(self.block_indent)
            .continuation_indent(self.continuation_indent)
            .trailing_comma_management_strategy(self.trailing_comma_management_strategy)
            .remove_unused_imports(self.remove_unused_imports)
            .preserve_lambda_breaks(self.preserve_lambda_breaks)
            .debugging_print_ops_after_formatting(self.debugging_print_ops_after_formatting)
    }
}

/// `FormattingOptions.Builder`.
#[derive(Clone, Copy, Debug)]
pub struct Builder {
    options: FormattingOptions,
}

impl Default for Builder {
    fn default() -> Self {
        Builder::new()
    }
}

impl Builder {
    pub fn new() -> Builder {
        Builder {
            options: FormattingOptions::new(
                FormattingOptions::DEFAULT_BLOCK_INDENT,
                FormattingOptions::DEFAULT_CONTINUATION_INDENT,
            ),
        }
    }

    pub fn max_width(mut self, max_width: i32) -> Builder {
        self.options.max_width = max_width;
        self
    }

    pub fn block_indent(mut self, block_indent: i32) -> Builder {
        self.options.block_indent = block_indent;
        self
    }

    pub fn continuation_indent(mut self, continuation_indent: i32) -> Builder {
        self.options.continuation_indent = continuation_indent;
        self
    }

    pub fn trailing_comma_management_strategy(mut self, strategy: TrailingCommaManagementStrategy) -> Builder {
        self.options.trailing_comma_management_strategy = strategy;
        self
    }

    pub fn remove_unused_imports(mut self, remove_unused_imports: bool) -> Builder {
        self.options.remove_unused_imports = remove_unused_imports;
        self
    }

    pub fn preserve_lambda_breaks(mut self, preserve_lambda_breaks: bool) -> Builder {
        self.options.preserve_lambda_breaks = preserve_lambda_breaks;
        self
    }

    pub fn debugging_print_ops_after_formatting(mut self, debugging_print_ops_after_formatting: bool) -> Builder {
        self.options.debugging_print_ops_after_formatting = debugging_print_ops_after_formatting;
        self
    }

    pub fn build(self) -> FormattingOptions {
        self.options
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TrailingCommaManagementStrategy {
    /// Do not manage trailing commas at all, only format what is already present.
    None,
    /// Only add trailing commas when necessary, but do not remove them.
    OnlyAdd,
    /// Fully manage trailing commas, adding and removing them where necessary.
    Complete,
}

impl TrailingCommaManagementStrategy {
    pub fn remove_redundant_trailing_commas(self) -> bool {
        self == TrailingCommaManagementStrategy::Complete
    }

    /// Enum constant name (`NONE`, `ONLY_ADD`, `COMPLETE`), as `valueOf` accepts it.
    pub fn name(self) -> &'static str {
        match self {
            TrailingCommaManagementStrategy::None => "NONE",
            TrailingCommaManagementStrategy::OnlyAdd => "ONLY_ADD",
            TrailingCommaManagementStrategy::Complete => "COMPLETE",
        }
    }

    /// `valueOf(name)`.
    pub fn value_of(name: &str) -> Option<TrailingCommaManagementStrategy> {
        [Self::None, Self::OnlyAdd, Self::Complete].into_iter().find(|s| s.name() == name)
    }
}

/// `NONE` -> "None", `ONLY_ADD` -> "Only add".
impl fmt::Display for TrailingCommaManagementStrategy {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let lower = self.name().replace('_', " ").to_lowercase();
        let mut chars = lower.chars();
        let first = chars.next().map(|c| c.to_uppercase().to_string()).unwrap_or_default();
        write!(f, "{first}{}", chars.as_str())
    }
}
