//! The name lists of `core/util/Composables.kt` (split off to keep that file short).

/// `ComposableNonEmittersList`: composables that emit content in their own window.
pub const COMPOSABLE_NON_EMITTERS_LIST: &[&str] =
    &["AlertDialog", "DatePickerDialog", "Dialog", "DropdownMenu", "ModalBottomSheetLayout", "ModalBottomSheet", "Popup"];

/// `ComposableEmittersList`: foundation, material, material3 and Accompanist composables that emit content.
pub const COMPOSABLE_EMITTERS_LIST: &[&str] = &[
    "BasicTextField",
    "Box",
    "Canvas",
    "ClickableText",
    "Column",
    "Icon",
    "Image",
    "Layout",
    "LazyColumn",
    "LazyRow",
    "LazyVerticalGrid",
    "Row",
    "Spacer",
    "Text",
    "BottomDrawer",
    "Button",
    "Card",
    "Checkbox",
    "CircularProgressIndicator",
    "Divider",
    "DropdownMenu",
    "DropdownMenuItem",
    "ExposedDropdownMenuBox",
    "ExtendedFloatingActionButton",
    "FloatingActionButton",
    "IconButton",
    "IconToggleButton",
    "LeadingIconTab",
    "LinearProgressIndicator",
    "ListItem",
    "ModalBottomSheetLayout",
    "ModalDrawer",
    "NavigationRail",
    "NavigationRailItem",
    "OutlinedButton",
    "OutlinedTextField",
    "RadioButton",
    "Scaffold",
    "ScrollableTabRow",
    "Slider",
    "SnackbarHost",
    "Surface",
    "SwipeToDismiss",
    "Switch",
    "Tab",
    "TabRow",
    "TextButton",
    "TopAppBar",
    "AssistChip",
    "DatePickerDialog",
    "DockedSearchBar",
    "ElevatedAssistChip",
    "ElevatedFilterChip",
    "ElevatedSuggestionChip",
    "ExposedDropdownMenuBox",
    "FilterChip",
    "HorizontalDivider",
    "InputChip",
    "InputField",
    "ModalBottomSheet",
    "NavigationBar",
    "NavigationBarItem",
    "PlainTooltip",
    "RichTooltip",
    "SearchBar",
    "SuggestionChip",
    "VerticalDivider",
    "BottomNavigation",
    "BottomNavigationContent",
    "BottomNavigationSurface",
    "FlowColumn",
    "FlowRow",
    "HorizontalPager",
    "HorizontalPagerIndicator",
    "SwipeRefresh",
    "SwipeRefreshIndicator",
    "TopAppBarContent",
    "TopAppBarSurface",
    "VerticalPager",
    "VerticalPagerIndicator",
    "WebView",
];

/// `CompositionLocalReferenceExpressions`.
pub const COMPOSITION_LOCAL_REFERENCE_EXPRESSIONS: &[&str] =
    &["staticCompositionLocalOf", "compositionLocalOf", "compositionLocalWithComputedDefaultOf"];

/// `RestartableEffects` (https://developer.android.com/jetpack/compose/side-effects#restarting-effects).
pub const RESTARTABLE_EFFECTS: &[&str] = &[
    "LaunchedEffect",
    "produceState",
    "DisposableEffect",
    "LifecycleEventEffect",
    "LifecycleResumeEffect",
    "LifecycleStartEffect",
    "produceRetainedState",
    "KeyedEffect",
];
